# Generated by Django 6.1.1 on 2026-09-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=60, verbose_name='Телефон')),
                ('messenger', models.CharField(blank=True, max_length=120, verbose_name='Telegram или WhatsApp')),
                ('company', models.CharField(blank=True, max_length=160, verbose_name='Компания')),
                ('project_type', models.CharField(choices=[('Новый сайт', 'Новый сайт'), ('Редизайн', 'Редизайн'), ('Лендинг', 'Лендинг'), ('Продвижение', 'Продвижение'), ('Яндекс Директ', 'Яндекс Директ'), ('SEO', 'SEO'), ('CRM и автоматизация', 'CRM и автоматизация'), ('Поддержка', 'Поддержка'), ('Другое', 'Другое')], default='Новый сайт', max_length=80, verbose_name='Тип проекта')),
                ('description', models.TextField(blank=True, verbose_name='Задача')),
                ('budget', models.CharField(blank=True, max_length=80, verbose_name='Бюджет')),
                ('attachment', models.FileField(blank=True, upload_to='lead-files/%Y/%m/', verbose_name='Файл')),
                ('source', models.CharField(blank=True, max_length=500, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
