# Generated by Django 6.1.1 on 2026-09-24 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_utm_campaign_lead_utm_content_lead_utm_medium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название проекта')),
                ('niche', models.CharField(blank=True, max_length=120, verbose_name='Ниша')),
                ('is_concept', models.BooleanField(default=True, verbose_name='Это концепт')),
                ('task', models.TextField(blank=True, verbose_name='Исходная задача')),
                ('work', models.TextField(blank=True, verbose_name='Что сделано')),
                ('result', models.TextField(blank=True, help_text='Указывайте только подтверждённые результаты; можно оставить пустым.', verbose_name='Результат')),
                ('technologies', models.CharField(blank=True, max_length=240, verbose_name='Технологии')),
                ('project_url', models.URLField(blank=True, verbose_name='Ссылка на проект')),
                ('image_url', models.URLField(blank=True, verbose_name='URL изображения')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Кейс или концепт',
                'verbose_name_plural': 'Кейсы и концепты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Частые вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Название пункта')),
                ('url', models.CharField(help_text='Например: /uslugi/ или https://example.ru', max_length=240, verbose_name='Ссылка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Меню сайта',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Главная'), ('services', 'Услуги'), ('development', 'Разработка сайтов'), ('real_estate', 'Сайты для агентств недвижимости'), ('promotion', 'Продвижение и реклама'), ('cases', 'Кейсы'), ('about', 'О студии'), ('contacts', 'Контакты'), ('privacy', 'Политика конфиденциальности')], max_length=32, unique=True, verbose_name='Страница')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='SEO Title')),
                ('description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
                ('content_html', models.TextField(blank=True, help_text='Необязательно. Если заполнить, это содержимое заменит стандартный макет выбранной страницы. Разрешён HTML; редактируйте только доверенным пользователям.', verbose_name='Содержимое страницы (HTML)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Страница опубликована')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Содержимое страницы',
                'verbose_name_plural': 'Страницы сайта',
                'ordering': ['page'],
            },
        ),
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Пакет')),
                ('audience', models.CharField(blank=True, max_length=240, verbose_name='Кому подходит')),
                ('included', models.TextField(blank=True, verbose_name='Что входит (каждый пункт с новой строки)')),
                ('timeline', models.CharField(blank=True, max_length=120, verbose_name='Примерный срок')),
                ('price_note', models.CharField(default='Стоимость после оценки задачи', max_length=160, verbose_name='Стоимость')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Пакет работ',
                'verbose_name_plural': 'Пакеты и тарифы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', max_length=8, verbose_name='Номер')),
                ('title', models.CharField(max_length=140, verbose_name='Этап')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Этап работы',
                'verbose_name_plural': 'Этапы работы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', max_length=8, verbose_name='Номер')),
                ('title', models.CharField(max_length=140, verbose_name='Направление')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Услуга продвижения',
                'verbose_name_plural': 'Продвижение и реклама',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RealtyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', max_length=8, verbose_name='Номер')),
                ('title', models.CharField(max_length=140, verbose_name='Возможность')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Функция для недвижимости',
                'verbose_name_plural': 'Возможности для недвижимости',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', max_length=8, verbose_name='Номер')),
                ('title', models.CharField(max_length=140, verbose_name='Услуга')),
                ('text', models.TextField(blank=True, verbose_name='Кому и какую задачу решает')),
                ('url', models.CharField(default='/uslugi/', max_length=240, verbose_name='Ссылка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='IT GROUP', max_length=120, verbose_name='Название бренда')),
                ('brand_tagline', models.CharField(default='Сайты и цифровые решения для бизнеса', max_length=240, verbose_name='Короткое описание')),
                ('phone', models.CharField(blank=True, max_length=80, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Ссылка на Telegram')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='Ссылка на WhatsApp')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=240, verbose_name='Адрес')),
                ('work_hours', models.CharField(blank=True, max_length=160, verbose_name='График работы')),
                ('requisites', models.TextField(blank=True, verbose_name='Реквизиты')),
                ('footer_text', models.CharField(blank=True, default='Сайты и цифровые решения, связанные с задачами бизнеса.', max_length=300, verbose_name='Текст в подвале')),
                ('primary_color', models.CharField(default='#417CFF', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Укажите цвет в формате #RRGGBB')], verbose_name='Основной акцентный цвет')),
                ('secondary_color', models.CharField(default='#52D6DC', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Укажите цвет в формате #RRGGBB')], verbose_name='Дополнительный акцентный цвет')),
                ('background_color', models.CharField(default='#0A0D14', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Укажите цвет в формате #RRGGBB')], verbose_name='Цвет фона')),
                ('yandex_metrika_id', models.CharField(blank=True, max_length=40, verbose_name='ID Яндекс Метрики')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
